import pymongo

client = pymongo.MongoClient()

db = client['pro1']
col = db['user']

#col.insert_one({"name": "rahul", "email": "rahul@gmail.com"})
col.insert_many([{"id": 1, "first_name": "Harriot", "last_name": "Storek", "email": "hstorek0@home.pl", "gender": "Female"},
                 {"id": 2, "first_name": "Maggie", "last_name": "Patkin",
                     "email": "mpatkin1@edublogs.org", "gender": "Female"},
                 {"id": 3, "first_name": "Worth", "last_name": "Mathiot",
                     "email": "wmathiot2@businessinsider.com", "gender": "Male"},
                 {"id": 4, "first_name": "Barbe", "last_name": "Dancer",
                  "email": "bdancer3@europa.eu", "gender": "Female"},
                 {"id": 5, "first_name": "Gennie", "last_name": "Heeks",
                  "email": "gheeks4@dropbox.com", "gender": "Female"},
                 {"id": 6, "first_name": "Beitris", "last_name": "Bakhrushin",
                  "email": "bbakhrushin5@wunderground.com", "gender": "Female"},
                 {"id": 7, "first_name": "Thor", "last_name": "Gladden",
                  "email": "tgladden6@taobao.com", "gender": "Male"},
                 {"id": 8, "first_name": "Sim", "last_name": "Giacopelo",
                  "email": "sgiacopelo7@cornell.edu", "gender": "Genderqueer"},
                 {"id": 9, "first_name": "Vin", "last_name": "Obeney",
                  "email": "vobeney8@amazonaws.com", "gender": "Male"},
                 {"id": 10, "first_name": "Cthrine", "last_name": "Chatres",
                  "email": "cchatres9@harvard.edu", "gender": "Agender"},
                 {"id": 11, "first_name": "Barnaby", "last_name": "Signori",
                  "email": "bsignoria@discovery.com", "gender": "Male"},
                 {"id": 12, "first_name": "Max", "last_name": "Gisburne",
                  "email": "mgisburneb@reuters.com", "gender": "Male"},
                 {"id": 13, "first_name": "Malcolm", "last_name": "Franzotto",
                  "email": "mfranzottoc@php.net", "gender": "Male"},
                 {"id": 14, "first_name": "Baxie", "last_name": "Cripps",
                  "email": "bcrippsd@mysql.com", "gender": "Male"},
                 {"id": 15, "first_name": "Ally", "last_name": "Cobbald",
                  "email": "acobbalde@walmart.com", "gender": "Female"},
                 {"id": 16, "first_name": "Federica", "last_name": "Fessier",
                  "email": "ffessierf@wp.com", "gender": "Female"},
                 {"id": 17, "first_name": "Dalli", "last_name": "Albers",
                  "email": "dalbersg@vk.com", "gender": "Male"},
                 {"id": 18, "first_name": "Eula", "last_name": "Leport",
                  "email": "eleporth@networksolutions.com", "gender": "Polygender"},
                 {"id": 19, "first_name": "Kellen", "last_name": "Bootton",
                  "email": "kboottoni@apache.org", "gender": "Female"},
                 {"id": 20, "first_name": "Rudd", "last_name": "Humphrey",
                  "email": "rhumphreyj@zimbio.com", "gender": "Male"},
                 {"id": 21, "first_name": "Taryn", "last_name": "Kinahan",
                  "email": "tkinahank@friendfeed.com", "gender": "Female"},
                 {"id": 22, "first_name": "Ashlee", "last_name": "Ferreres",
                  "email": "aferreresl@etsy.com", "gender": "Female"},
                 {"id": 23, "first_name": "Audie", "last_name": "Burren",
                  "email": "aburrenm@ustream.tv", "gender": "Female"},
                 {"id": 24, "first_name": "Brandie", "last_name": "Phifer",
                  "email": "bphifern@dedecms.com", "gender": "Female"},
                 {"id": 25, "first_name": "Barris", "last_name": "Simkins",
                  "email": "bsimkinso@ox.ac.uk", "gender": "Male"},
                 {"id": 26, "first_name": "Ephraim", "last_name": "Fernao",
                  "email": "efernaop@studiopress.com", "gender": "Male"},
                 {"id": 27, "first_name": "Linell", "last_name": "Ianitti",
                  "email": "lianittiq@xing.com", "gender": "Female"},
                 {"id": 28, "first_name": "Devy", "last_name": "McGreil",
                  "email": "dmcgreilr@washington.edu", "gender": "Genderqueer"},
                 {"id": 29, "first_name": "Nadean", "last_name": "Lawly",
                  "email": "nlawlys@studiopress.com", "gender": "Female"},
                 {"id": 30, "first_name": "Verene", "last_name": "Mitro",
                  "email": "vmitrot@t-online.de", "gender": "Genderqueer"},
                 {"id": 31, "first_name": "Sosanna", "last_name": "Lindup",
                  "email": "slindupu@reference.com", "gender": "Female"},
                 {"id": 32, "first_name": "Anet", "last_name": "Murrill",
                  "email": "amurrillv@youku.com", "gender": "Female"},
                 {"id": 33, "first_name": "Indira", "last_name": "Crotty",
                  "email": "icrottyw@bbb.org", "gender": "Female"},
                 {"id": 34, "first_name": "Gennifer", "last_name": "Georgescu",
                  "email": "ggeorgescux@cbsnews.com", "gender": "Female"},
                 {"id": 35, "first_name": "Aggi", "last_name": "Dennick",
                  "email": "adennicky@uiuc.edu", "gender": "Female"},
                 {"id": 36, "first_name": "Clem", "last_name": "Ondra",
                  "email": "condraz@toplist.cz", "gender": "Female"},
                 {"id": 37, "first_name": "Harwell", "last_name": "Maxwaile",
                  "email": "hmaxwaile10@tinypic.com", "gender": "Male"},
                 {"id": 38, "first_name": "Natty", "last_name": "Merriment",
                  "email": "nmerriment11@comsenz.com", "gender": "Male"},
                 {"id": 39, "first_name": "Alina", "last_name": "Cestard",
                  "email": "acestard12@e-recht24.de", "gender": "Female"},
                 {"id": 40, "first_name": "Anthony", "last_name": "Toupe",
                  "email": "atoupe13@indiegogo.com", "gender": "Male"},
                 {"id": 41, "first_name": "Shayne", "last_name": "Elms",
                  "email": "selms14@exblog.jp", "gender": "Genderqueer"},
                 {"id": 42, "first_name": "Fredi", "last_name": "Addicott",
                  "email": "faddicott15@shutterfly.com", "gender": "Female"},
                 {"id": 43, "first_name": "Mozes", "last_name": "Morey",
                  "email": "mmorey16@bloomberg.com", "gender": "Male"},
                 {"id": 44, "first_name": "Arlyne", "last_name": "Figger",
                  "email": "afigger17@blogtalkradio.com", "gender": "Female"},
                 {"id": 45, "first_name": "Turner", "last_name": "Murrill",
                  "email": "tmurrill18@zdnet.com", "gender": "Male"},
                 {"id": 46, "first_name": "Loreen", "last_name": "Lody",
                  "email": "llody19@homestead.com", "gender": "Female"},
                 {"id": 47, "first_name": "Cristal", "last_name": "Jaeggi",
                  "email": "cjaeggi1a@goo.gl", "gender": "Female"},
                 {"id": 48, "first_name": "Aldis", "last_name": "Parsisson",
                  "email": "aparsisson1b@plala.or.jp", "gender": "Male"},
                 {"id": 49, "first_name": "Berti", "last_name": "Checcuzzi",
                  "email": "bcheccuzzi1c@printfriendly.com", "gender": "Female"},
                 {"id": 50, "first_name": "Coretta", "last_name": "Billinge",
                  "email": "cbillinge1d@pagesperso-orange.fr", "gender": "Female"},
                 {"id": 51, "first_name": "Chris", "last_name": "Deave",
                  "email": "cdeave1e@cyberchimps.com", "gender": "Female"},
                 {"id": 52, "first_name": "Lockwood", "last_name": "Tegeller",
                  "email": "ltegeller1f@springer.com", "gender": "Male"},
                 {"id": 53, "first_name": "Kelvin", "last_name": "Dacre",
                  "email": "kdacre1g@prlog.org", "gender": "Male"},
                 {"id": 54, "first_name": "Phaidra", "last_name": "Bradshaw",
                  "email": "pbradshaw1h@buzzfeed.com", "gender": "Female"},
                 {"id": 55, "first_name": "Gamaliel", "last_name": "Parslow",
                  "email": "gparslow1i@desdev.cn", "gender": "Male"},
                 {"id": 56, "first_name": "Maggi", "last_name": "Crowcroft",
                  "email": "mcrowcroft1j@harvard.edu", "gender": "Female"},
                 {"id": 57, "first_name": "Ezmeralda", "last_name": "Iapico",
                  "email": "eiapico1k@miitbeian.gov.cn", "gender": "Female"},
                 {"id": 58, "first_name": "Vincenty", "last_name": "Houseman",
                  "email": "vhouseman1l@jigsy.com", "gender": "Male"},
                 {"id": 59, "first_name": "Kippie", "last_name": "Kernoghan",
                  "email": "kkernoghan1m@ask.com", "gender": "Male"},
                 {"id": 60, "first_name": "Holmes", "last_name": "Brighouse",
                  "email": "hbrighouse1n@altervista.org", "gender": "Male"},
                 {"id": 61, "first_name": "Lilly", "last_name": "Kirgan",
                  "email": "lkirgan1o@1und1.de", "gender": "Agender"},
                 {"id": 62, "first_name": "Susan", "last_name": "Bodemeaid",
                  "email": "sbodemeaid1p@furl.net", "gender": "Genderfluid"},
                 {"id": 63, "first_name": "Penrod", "last_name": "Kilsby",
                  "email": "pkilsby1q@auda.org.au", "gender": "Male"},
                 {"id": 64, "first_name": "Chickie", "last_name": "Sandaver",
                  "email": "csandaver1r@jalbum.net", "gender": "Female"},
                 {"id": 65, "first_name": "Sansone", "last_name": "Falconbridge",
                  "email": "sfalconbridge1s@vistaprint.com", "gender": "Male"},
                 {"id": 66, "first_name": "Thorpe", "last_name": "Barles",
                  "email": "tbarles1t@nbcnews.com", "gender": "Male"},
                 {"id": 67, "first_name": "Amandy", "last_name": "Rebbeck",
                  "email": "arebbeck1u@reuters.com", "gender": "Female"},
                 {"id": 68, "first_name": "Jobie", "last_name": "Criple",
                  "email": "jcriple1v@skype.com", "gender": "Female"},
                 {"id": 69, "first_name": "Kati", "last_name": "Attoc",
                  "email": "kattoc1w@msu.edu", "gender": "Genderfluid"},
                 {"id": 70, "first_name": "Elnora", "last_name": "Yardley",
                  "email": "eyardley1x@opera.com", "gender": "Female"},
                 {"id": 71, "first_name": "Fremont", "last_name": "Schruyers",
                  "email": "fschruyers1y@ovh.net", "gender": "Male"},
                 {"id": 72, "first_name": "Kirby", "last_name": "Melody",
                  "email": "kmelody1z@myspace.com", "gender": "Male"},
                 {"id": 73, "first_name": "Veda", "last_name": "Steinham",
                  "email": "vsteinham20@paypal.com", "gender": "Female"},
                 {"id": 74, "first_name": "Agnese", "last_name": "Arendsen",
                  "email": "aarendsen21@sohu.com", "gender": "Female"},
                 {"id": 75, "first_name": "Pall", "last_name": "Blaxley",
                  "email": "pblaxley22@ted.com", "gender": "Male"},
                 {"id": 76, "first_name": "Tallou", "last_name": "Karus",
                  "email": "tkarus23@statcounter.com", "gender": "Female"},
                 {"id": 77, "first_name": "Murray", "last_name": "Wringe",
                  "email": "mwringe24@github.com", "gender": "Male"},
                 {"id": 78, "first_name": "Leighton", "last_name": "Gregolotti",
                  "email": "lgregolotti25@toplist.cz", "gender": "Male"},
                 {"id": 79, "first_name": "Alvera", "last_name": "Le-Good",
                  "email": "alegood26@goo.ne.jp", "gender": "Female"},
                 {"id": 80, "first_name": "Rea", "last_name": "Colpus",
                  "email": "rcolpus27@dyndns.org", "gender": "Female"},
                 {"id": 81, "first_name": "Hamish", "last_name": "Scown",
                  "email": "hscown28@tuttocitta.it", "gender": "Male"},
                 {"id": 82, "first_name": "Jayson", "last_name": "Conigsby",
                  "email": "jconigsby29@infoseek.co.jp", "gender": "Male"},
                 {"id": 83, "first_name": "Emmalynne", "last_name": "Edsall",
                  "email": "eedsall2a@nsw.gov.au", "gender": "Bigender"},
                 {"id": 84, "first_name": "Margarete", "last_name": "Denizet",
                  "email": "mdenizet2b@nsw.gov.au", "gender": "Female"},
                 {"id": 85, "first_name": "Denis", "last_name": "Timberlake",
                  "email": "dtimberlake2c@alibaba.com", "gender": "Male"},
                 {"id": 86, "first_name": "Carlos", "last_name": "Easum",
                  "email": "ceasum2d@yolasite.com", "gender": "Genderqueer"},
                 {"id": 87, "first_name": "Kata", "last_name": "Gallahue",
                  "email": "kgallahue2e@seesaa.net", "gender": "Female"},
                 {"id": 88, "first_name": "Constantin", "last_name": "Amoore",
                  "email": "camoore2f@google.co.uk", "gender": "Male"},
                 {"id": 89, "first_name": "Brynn", "last_name": "Perez",
                  "email": "bperez2g@constantcontact.com", "gender": "Female"},
                 {"id": 90, "first_name": "Syd", "last_name": "Van der Linde",
                  "email": "svanderlinde2h@amazonaws.com", "gender": "Male"},
                 {"id": 91, "first_name": "Shaine", "last_name": "Yorke",
                  "email": "syorke2i@google.nl", "gender": "Male"},
                 {"id": 92, "first_name": "Sal", "last_name": "Bunch",
                  "email": "sbunch2j@mapy.cz", "gender": "Male"},
                 {"id": 93, "first_name": "Huntley", "last_name": "Siverns",
                  "email": "hsiverns2k@wsj.com", "gender": "Male"},
                 {"id": 94, "first_name": "Hester", "last_name": "Clinton",
                  "email": "hclinton2l@myspace.com", "gender": "Female"},
                 {"id": 95, "first_name": "Catherine", "last_name": "Blenkin",
                  "email": "cblenkin2m@va.gov", "gender": "Female"},
                 {"id": 96, "first_name": "Kylen", "last_name": "Delia",
                  "email": "kdelia2n@ovh.net", "gender": "Female"},
                 {"id": 97, "first_name": "Findlay", "last_name": "Canet",
                  "email": "fcanet2o@slashdot.org", "gender": "Male"},
                 {"id": 98, "first_name": "Randy", "last_name": "Janic",
                  "email": "rjanic2p@devhub.com", "gender": "Male"},
                 {"id": 99, "first_name": "Artemis", "last_name": "Turpey",
                  "email": "aturpey2q@walmart.com", "gender": "Male"},
                 {"id": 100, "first_name": "Ilysa", "last_name": "Lyttle", "email": "ilyttle2r@wordpress.org", "gender": "Female"}])
print("document inserted succesfully")
