# Generated by Django 4.2.7 on 2023-12-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='esal',
            field=models.IntegerField(),
        ),
    ]
