# Generated by Django 4.2.7 on 2023-12-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_alter_employee_esal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eemil',
            new_name='eemail',
        ),
    ]
