# Generated by Django 4.2.7 on 2023-12-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=32)),
                ('uloc', models.CharField(max_length=32)),
            ],
        ),
    ]
